# Generated by Django 5.0.6 on 2024-05-19 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('file', models.FileField(upload_to='uploaded_files/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'uploaded_file',
                'db_table_comment': 'Table to store uploaded files',
                'ordering': ['name'],
            },
        ),
    ]
